version: '3'
services:
    wordpress:
        container_name: int-wordpress
        build: .
        volumes:
            - .:/bedrock
        env_file: .env
        environment:
            WP_ENV: development
            VIRTUAL_HOST: ${SERVER_NAME}
            WP_HOME: http://${SERVER_NAME}
            WP_SITEURL: http://${SERVER_NAME}/wp
            SMTP_HOST: mailcatcher
            SMTP_PORT: 1025
            DB_NAME: wordpress
            DB_USER: wordpress
            DB_PASSWORD: wordpress
            DB_HOST: mysql
            S3SignUrls: S3SignUrls
        depends_on:
            - mysql
            - mailcatcher
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse

    mysql:
        container_name: int-mariadb
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        volumes:
            - database:/var/lib/mysql
        ports:
            - "9000:3306"

    mailcatcher:
        container_name: int-mailcatcher
        image: schickling/mailcatcher
        environment:
            VIRTUAL_HOST: mail.${SERVER_NAME}
            VIRTUAL_PORT: 1080

    phpmyadmin:
        container_name: int-phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            VIRTUAL_HOST: phpmyadmin.${SERVER_NAME}
            VIRTUAL_PORT: 9191
            PMA_HOST: mysql
        depends_on:
            - mysql
        ports:
            - "9191:80"

    elasticsearch:
        container_name: int-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
        environment:
            VIRTUAL_HOST: elasticsearch.${SERVER_NAME}
            VIRTUAL_PORT: 9200
            xpack.security.enabled: false
            discovery.type: single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
    kibana:
        container_name: int-kibana
        image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}
        environment:
            VIRTUAL_HOST: kibana.${SERVER_NAME}
            VIRTUAL_PORT: 5601
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
        ports:
            - "5610:5610"
        depends_on:
            - elasticsearch

volumes:
    elasticsearch-data:
    database:
        driver: local
